// Provider-owned, bilingual explanations; the assembler UI only renders this contract.
const guide = (contains, origin, editable, editAt) => ({ contains, origin, editable, editAt })
export const contentGuides = {
 'native-system': guide(['DSH 当前基础指令及已注册插件提供的系统段落。','Current DSH instructions and system sections contributed by registered plugins.'],['DSH 官方系统提示词装配；预览中逐段显示提供方。','Official DSH system prompt assembly; preview identifies each section provider.'],['不能在此编辑自动生成的正文。','Generated content cannot be edited here.'],['在 DSH 或对应插件的设置中修改；预览查看具体段落和提供方。','Change DSH or the contributing plugin settings; inspect section providers in preview.']),
 history: guide(['此前的用户消息、助手回复和工具结果，保留原始角色。','Previous user messages, assistant replies and tool results with original roles.'],['当前 DSH 会话的持久历史。','Durable history of the current DSH session.'],['不能在装配策略中改写历史正文。','History cannot be rewritten in assembly rules.'],['到 DSH 对话或轨迹查看；历史修改能力由 DSH 提供。','View DSH Conversation or Trace; history editing capabilities belong to DSH.']),
 input: guide(['本次请求新提交的输入；预览不包含尚未发送的草稿。','New input submitted for this request; preview excludes unsent drafts.'],['DSH 本步输入消息。','DSH current-step input messages.'],['发送前可修改输入框草稿。','The composer draft is editable before sending.'],['在 DSH 消息输入框修改。','Edit the DSH message composer.']),
 preset: guide(['当前预设中启用的提示词正文、角色覆盖，以及角色、世界书和历史插槽引用。','Enabled prompt text, character overrides and character/world-book/history slot references from the selected preset.'],['当前会话在 Tavern 中绑定的 ST 提示词预设。','ST prompt preset bound to the current Tavern session.'],['可以编辑预设条目；这里不修改其正文。','Preset entries are editable outside this assembly rule.'],['DT → 预设：选择当前绑定的预设，编辑对应提示词条目并保存。','DT → Preset: select the bound preset, edit its prompt entries and save.']),
 character: guide(['角色描述、性格、场景、对话示例及角色系统指令；按开场与深度配置提供额外内容。','Character description, personality, scenario, examples and system instructions, with greeting/depth content when configured.'],['当前会话选中的 Tavern 角色卡及其会话选择设置。','Selected Tavern character card and session selection settings.'],['角色卡字段可以编辑；历史中的已发送内容不会改写。','Character fields are editable; recorded messages remain unchanged.'],['DT → 角色卡：打开当前角色，修改对应字段；开场参考与偏好在会话角色设置中调整。','DT → Characters: edit the selected card; adjust greeting references and preferences in session character settings.']),
 persona: guide(['当前用户设定的描述正文。','Description text of the selected user persona.'],['当前会话在 Tavern 中选中的用户设定。','Tavern user persona selected for this session.'],['可以编辑用户设定描述。','The persona description is editable.'],['DT → 用户：选择当前用户设定，修改描述并保存。','DT → User: select the current persona, edit its description and save.']),
 worldbook: guide(['绑定世界书中通过启用、关键词、概率、预算及管理规则的条目正文；包含符合条件的角色内嵌条目。','Active entries passing enablement, keyword, probability, budget and management rules, including eligible character-embedded entries.'],['当前会话、角色、用户设定和预设绑定的世界书；预览逐条显示资源 ID 和条目。','World books bound through session, character, persona and preset; preview identifies resource IDs and entries.'],['世界书条目正文和激活设置可以编辑。','Entry text and activation settings are editable.'],['DT → 世界书编辑对应书和条目；角色内嵌书在 DT → 角色卡的内嵌世界书中修改。记忆管理只调整管理规则。','Edit books and entries in DT → World Books; edit embedded books in DT → Characters. Memory Manager changes management rules.']),
 phi: guide(['角色卡后置指令、预设 jailbreak 条目，以及下方填写的策略追加指令。','Character post-history instructions, preset jailbreak and additional strategy text below.'],['当前角色、当前预设，以及这份装配策略的追加文本。','Selected character, preset and this strategy’s additional text.'],['追加文本在此编辑；角色和预设正文在各自编辑器中修改。','Additional text is editable here; source text is edited in its own editor.'],['DT → 角色卡的后置指令，或 DT → 预设的 Post-History Instructions / jailbreak；策略追加内容使用下方输入框。','DT → Characters post-history instructions or DT → Preset Post-History Instructions / jailbreak; edit strategy additions below.']),
 'tavern.mvu/state': guide(['当前绑定的每个 MVU 实例的 stat_data（JSON 状态值），以及该资源的变量更新输出指令；未配置指令时使用内置 JSONPatch 指令。','stat_data JSON values and variable-update output instructions for each bound MVU instance; unset instructions use the built-in JSONPatch instructions.'],['角色卡 InitVar 或显式 MVU 配置初始化的当前会话实例；状态随后由助手变量更新、卡片操作和手动编辑维护。更新指令来自该实例保留的 MVU 资源定义 instructions，未配置时用内置指令。','Current session instances initialized from character InitVar or explicit MVU configuration; assistant updates, card actions and manual edits maintain state. Instructions come from the instance’s retained MVU resource instructions definition, or the built-in default.'],['当前变量可手动编辑；历史状态只读。更新指令没有界面编辑器，不能在此修改。','Current variables are editable; historical state is read-only. Update instructions have no UI editor and cannot be changed here.'],['Tavern Trace → 最新轮次 → MVU 变量与变更 → 当前变量：逐行编辑并保存 JSON。首次声明资源时可在 Tavern 插件 mvu.resources 中设置 instructions；既有实例的更新指令目前没有受支持的编辑入口，重启或改 InitVar 不会覆盖其持久定义。','Tavern Trace → latest turn → MVU variables and changes → Current variables: edit and save JSON per row. Set instructions when first declaring a resource in Tavern plugin mvu.resources. Existing instance instructions currently have no supported editing entry point; restart or InitVar edits do not overwrite their durable definition.']),
 'pmp-dsh-tavern/prompt-template': guide(['已启用且绑定当前会话的模板 content，经受限 EJS 求值及 Tavern 宏展开后的正文。','Rendered content of enabled templates bound to this session, using restricted EJS and Tavern macros.'],['Tavern 模板资源；既有资源以插件存储目录的 prompt-templates.json 为准。','Tavern template resources; existing resources are stored in the plugin storage directory’s prompt-templates.json.'],['模板正文可编辑；启用、会话绑定和变量来源没有此处的编辑入口。','Template content is editable; enablement, session bindings and variable sources are configured separately.'],['记忆管理 → 对应 prompt-template 资源 → 内容编辑器修改正文（需安装管理器）。无管理器时使用公开模板 update API；资源绑定与启用配置需停 Host 后修改 prompt-templates.json，再重启。','Memory Manager → corresponding prompt-template resource → content editor (requires Manager). Without Manager use the public template update API. Stop Host to edit bindings/enablement in prompt-templates.json, then restart.']),
 'memory-manager.resources': guide(['通用检索策略本次匹配后返回的非空资源文本；来源自行装配的 MVU、世界书与模板不重复输出。','Nonempty text returned by matching generic retrieval strategies; source-assembled MVU, world books and templates are excluded.'],['记忆管理已配置的资源和读取策略；预览显示每个实际贡献的资源 ID。','Configured Memory Manager resources and retrieval strategies; preview identifies each contributing resource ID.'],['读取规则可以编辑；正文是否可编辑由资源提供方声明，不能在此编辑聚合结果。','Retrieval rules are editable; resource providers determine content editability. Aggregated output cannot be edited here.'],['记忆管理 → 对应资源 → 读取 retrieve 修改检索规则；支持写入的资源使用该页内容编辑器，否则到来源插件编辑。','Memory Manager → resource → Retrieve to edit retrieval rules; use its content editor when supported, otherwise edit in the provider plugin.']),
}
